project:
  type: website
  output-dir: docs

website:
  title: "My Project 3"
  navbar:
    left:
      - text: "EDA"
        file: EDA.qmd
      - text: "Modeling"
        file: Modeling.qmd
  page-navigation: true